# Site settings
title: Vote Mote
tag_text: Vote Monte 
description: Vote *Monte* for Academic Affairs Officer!


url: "http://votemonte.github.io"

# Build settings
markdown: kramdown

exclude: ["README.md"]
